### ISSUE TITLE
where to setup CLIENT_ID and CLIENT_SECRET ?

### ISSUE THREAD

**Issue by doricardo** [NotYasho/Spotify_Playlist_Downloader#2]
Hi i'm not familiar with tha kind of those setups, where can I have to setup CLIENT_ID and CLIENT_SECRET ? 

actuallly, how to set os.environ['SPOTIFY_CLIENT'] and os.environ['SPOTIFY_REFRESH_TOKEN']

**Comment by SHOWHEROGAMES** [comment]
make a file with name `.env`

**Comment by Yasho022** [comment]
[](https://camo.githubusercontent.com/cf9ca92176ec4ca244cfaf0ec3e2cc47c53668fdc551c79c4b5ab2332462f161/68747470733a2f2f69322e70617374652e706963732f464e4f51592e706e67)[](https://camo.githubusercontent.com/bb07b24709e8d8244b0be9e91d31b1a8db0d8f4d937e1769ea16ec0cbf39bbc7/68747470733a2f2f69322e70617374652e706963732f464e4f534b2e706e67)Search for environment variables for your account in the start menu.

Click on Edit environment variables for your account.

In the User Variables, Select Path and click Edit.



Click New and add the pycmd/bin/ folder to the Path.



Click OK.

Restart your terminal.
